name: Django CD

on:
  workflow_run:
    workflows: [ "Django CI"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: connect ec2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd /home/cicd/code/django
            git pull
            gunicorn config.wsgi:application --bind 0.0.0.0:8000 --reload --daemon